version: '3'
services:
    confluence:
        image: "atlassian/confluence-server:8.0.2"
        container_name: confluence
        depends_on:
            - db
        volumes: 
            - ./atlassian-agent.jar:/var/atlassian/atlassian-agent.jar
            - /var/atlassian/application-data/confluence:/var/atlassian/application-data/confluence
        environment:
            - JAVA_OPTS="-javaagent:/var/atlassian/atlassian-agent.jar"
            - JVM_MINIMUM_MEMORY=2048m
            - JVM_MAXIMUM_MEMORY=2048m
            - JVM_RESERVED_CODE_CACHE_SIZE=512m
        ports: 
            - "8090:8090"
            - "8091:8091"
        restart: always
    db:
        image: postgres:latest
        container_name: postgres-db
        ports:
          - "5432:5432"
        restart: always
        environment:
          - POSTGRES_PASSWORD=113661
        volumes:
          - /home/app/confluence/pgsql-data:/var/lib/postgresql/data
